### ISSUE TITLE
Majority Element of an Array (C++)

### ISSUE THREAD

**Issue by Stanish4Ever** [TechOUs/AlgoHeist#239]
A majority element in an array A[] of size n is an element that appears more than n/2 times (and hence there is at most one such element)
For example : 
{7,7,7,7,3,4}
Majority Element is 7 appears more than 3 times that is size of the array
{2,3,3,4,5,6}
No Majority Element.  

I have decided to use Moore's Voting Algorithm to solve this problem.

Please assign me this issue. 
Thank you.

**Comment by 1-Sanchit-1** [comment]
can i contribute?

**Comment by ritik-rkg** [comment]
Majority Element Using [Moore’s Voting Algorithm]
This is a two-step process:

The first step gives the element that may be the majority element in the array. If there is a majority element in an array, then this step will definitely return majority element, otherwise, it will return candidate for majority element.
Check if the element obtained from the above step is the majority element. This step is necessary as there might be no majority element.

I want to solve this problem and add a proper code for this problem with comments in each line explaining the code properly and making it beginner friendly.
Also this will be my first pr under hacktoberfest2022 could you please assign this to me under hacktoberfest2022

Thanks
Ritik Kumar Gupta

**Comment by Rishi0510** [comment]
Please assign me this issue under Hacktoberfest.

**Comment by falguni300103** [comment]
Can you please assign this issue to me?

**Comment by Avy2808** [comment]
Can you please assign this issue to me. I would like to contribute to this.
